# -*- fill-column: 80; org-confirm-babel-evaluate: nil -*-

#+TITLE:     Resume
#+AUTHOR:    Oleg Sivokon
#+EMAIL:     olegsivokon@gmail.com
#+DATE:      <2015-05-19 Tue>
#+DESCRIPTION: My resume
#+KEYWORDS: Resume, job, employment, cv
#+OPTIONS: toc:nil
#+LaTeX_CLASS: article
#+LaTeX_HEADER: \usepackage[scaled]{helvet}
#+LaTeX_HEADER: \renewcommand*\familydefault{\sfdefault}

* Contact Information
  | Name:       | Oleg Sivokon                   |
  | Birth date: | 23, 06, 1978                   |
  | Cell phone: | +972 (0) 544-563314            |
  | Email:      | [[mailto:olegsivokon@gmail.com][olegsivokon@gmail.com]]          |
  | Address:    | Florentin 50, Tel Aviv, Israel |

  /You can find an up-to-date electronic copy of this document at/
  
  https://github.com/wvxvw/resume

#+BEGIN_LATEX
\clearpage
#+END_LATEX

* Work History
  
** PowToon Ltd.
   + What PowToon does :: PowToon is a software as service kind of start-up
        which specializes in presentation software.
   + What I did there :: I worked as a programmer.
     - Relevant
       - I wrote and maintained build scripts in Ant and Gradle.
       - I wrote tests using Selenium server.
       - I managed Jenkins continuous integration server.
     - Irrelevant
       - I wrote a SWF format encoder (using Haxe programming language).
       - I wrote several scripts to extract some statistics from the company's
         user database related to customers' sentiment analysis.
             
   + When did I do it :: January 2014--May 2015

** TransGaming Inc.
   + What TransGaming does :: TransGaming is a game development company which
        specializes in embedded software, ``smart'' television in particular.
   + What I did there :: I worked as a programmer.
     - Relevant
       - I wrote number of tests for Selenium server (using Python programming
         language).
       - I wrote a player AI which played the games in order to test their
         performance.
     - Irrelevant
       - I wrote a game portal (using TypeScript programming language).
       - I re-wrote a Luxor game to be used for testing and bench-marking
         on television sets supporting WebKit, Presto or Geko (using JavaScript
         programming language).
             
   + When did I do it :: April 2013--2013 (less than a year)
   
** Rounds
   + What Rounds does :: Rounds develops a video chat. Their product is available
        in a number of ways, such as through a web client interface or a mobile
        phone app.
   + What I did there :: I worked as a programmer.
     - Relevant
       - I wrote a mock server in order to leverage functional testing for the
         client-server interaction (using Python programming language).
       - I wrote a test chat client (using Erlang programming language).
     - Irrelevant
       - I wrote the communication part of the client (using ActionScript
         programming language).
             
   + When did I do it :: December 2010 – August 2011 (9 months)

** Other Jobs
   - HP (Hewlett Packard) :: I worked for almost a year in HP office in Yehud.
        during this time I worked on a Flex front-end for a large accounting
        application.  I also wrote some Java code related to client-server
        communication.
   - Mishloha :: I worked there very briefly.  The company was hoping to transition
        their old infrastructure written in ASP Classic (both VB and JScript) to
        Ruby on Rails, but they gave up their project.  They also had a sizable
        amount of code written in PHP.  My job there mostly included a failed
        attempt at cleaning up the layers of cruft left by bygone developers.
   - Zibaba :: I freelanced there preparing the site for i18n.
   - AdItAll :: AdItAll is a SaaS company which provides video editing tools for
        amateurs.  I've worked on the client side of the project.
   - Gazit Studio :: My first programming job in a small shop, which develops
        personal and small-business web-sites.  I worked on the client-side.

* Frequently Asked Questions
  + Q :: Am I familiar with web stack (HTML, CSS, JavaScript)?
  + A :: Yes, but I prefer to do something else for living.

  + Q :: Most of my experience indicates I worked on client side, why do I want
       to switch to development and operations or Python?
  + A :: Client-side development, historically, was always left to the armature
       programmers.  It uses technologies which don't require any skill or
       knowledge on the part of the programmer.  On top of it, the programs are
       not judged by their programming merits, but mostly rely on the subjective
       ``feeling'', based primarily on the work of the graphic designer.

  + Q :: How many programming languages do I know? Please give us a list.
  + A :: I certainly know more than you do.  An exhaustive list would bore you
       to death with the names you don't know how to read.  It's easier to
       tell which languages I consciously tried to avoid.
    - I don't like C++.  It's an over-marketed very poorly designed language.
    - I will not write in C#, because writing in C# implies working on MS Windows,
      and that's just immoral.  I've sinned enough already, I'm not looking to
      cooperate with more corrupt enterprises on top of it.  The argument,
      of course, extends to the entire .NET platform as well as Obj-C, and other
      such monsters.
    - I don't know Pascal.  Everyone since the don of the programming era seems
      to be happy writing pseudo-code in broken likelihood of Pascal.  This is
      something I can't stand about this language.  Use FORTRAN, motherlovers,
      be authentic!

  + Q :: Do I have any Linux experience?
  + A :: The answer should be obvious by now, but if it isn't, then here it is:
       Yes.

  + Q :: Do I know any SQL?
  + A :: Yes I do.

  + Q :: And NoSQL?
  + A :: Yes, quite a lot, actually.

* Courses
  I took several online courses from Coursera, Udacity and edX, which required
  me to complete programming assignments in Python.

  I took a complete series of courses in statistics at edX (three courses),
  the data scientist toolbox course at Coursera (six short courses), machine
  learning at Udacity, introduction to algorithms (two courses) at Coursera.

  I also volunteered for SCons project, writing an ActionScript plugin for it.
  (SCons is an extensible build system written in Python).

  Two years ago I interviewed for a position of Python programmer at Walla.
  They requested that I write a small test project, which I did.  The project,
  although somewhat outdated, is still available for viewing:
  https://github.com/wvxvw/intj.

  I am currently studying in Open University of Israel, mathematics faculty,
  about to finish my first year.

* Hobbies
  - NLP
  - Computational linguistics
  - Moral philosophy
  - General AI
  - Graphs
