# -*- fill-column: 80; org-latex-hyperref-template: nil -*-

#+DESCRIPTION: My resume
#+KEYWORDS: Resume, job, employment, cv
#+OPTIONS: toc:nil
#+LaTeX_CLASS: moderncv

#+BEGIN_LaTeX
\makecvtitle
#+END_LaTeX

* Technological Mastery

** Languages
   ActionScript, C, Clojure, Common Lisp, Emacs Lisp, Erlang, Forth, Haskell,
   Haxe, Java, JavaScript, Mercury, OCaml, PHP, Prolog, Python, Ruby, Scala,
   Scheme, Shell.

** Mathematics And Statistics
   J, Julia, Maxima, Octave (Matlab), R (S).

** Related Technologies
   Data representation formats (XML, YAML, JSON, RDF, AMF), Graph databases,
   Network protocols (TCP, UDP, HTTP, FTP), Relational databases (SQL), Web
   stack (HTML, CSS).

** Programming Environments
   Eclipse, Emacs, Intellij IDEA, Vim, Visual Studio.

** Operating Systems
    Android, GNU/Linux, Mac OS, Microsoft Windows.

** Infrastructure
   Ant, Maven, Gradle, Make, Grunt, Jenkins, JIRA, Redmine, Track, Mediawiki,
   Bugzilla, Selenium, Flex Unit, JUnit, unittest (Python), 5am, Cucumber, Git,
   Subversion, Mercurial, Perforce, Bazaar.

* Work History
  
** Programmer
   #+BEGIN_LaTeX
   \cventry{2014--2015}{Haxe, ActionScript, Python}{PowToon Ltd}{}{}{}
   #+END_LaTeX

   - Major application component (the player) in Haxe (compiled to Flash and
     C++).
   - Infrastructure code s.a. build scripts, automated test generation and
     continuous integration server setup using Ant, Grdle and utilities written
     in Python, s.a. Fabric.
   - Designs for the product.

#+BEGIN_LaTeX
\newpage
#+END_LaTeX

** Programmer
   #+BEGIN_LaTeX
   \cventry{2013}{JavaScript, TypeScript, Python}{TransGaming Inc}{}{}{}
   #+END_LaTeX

   - Game portal for ``Smart TV'' using TypeScript.
   - Performance tester program for ``Smart TV'' using Python.
   - Automated build using Ant.
   - Usage statistic aggregation based on Google Analytics using JavaScript.

** Programmer
   #+BEGIN_LaTeX
   \cventry{2010--2011}{ActionScript, Erlang}{Rounds}{}{}{}
   #+END_LaTeX

   - Communication component of the video chat using ActionScript.
   - Testing server and utility programs for automated testing using Erlang.
   - Small natural language processing program for use in promotion of company's
     product.

* Courses
  + Open University of Israel :: Mathematics.
  + Coursera and edX ::  Several MOOC classes related to programming including
       Data Scientists Toolbox, Statistics, Data Analysis, Machine Learning.

* Volunteering And Community Work
  + SCons :: Plugin for building ActionScript projects.
  + Adobe Community Advisory Board :: Moderator of documentation and Q/A site.
  + StackExchange :: Active participant in the  Emacs Q/A site.

* Work Examples
  My Github profile:
  https://github.com/wvxvw/.

* Hobbies
  NLP, Computational linguistics, Moral philosophy, General AI, Graphs.
